all:
  vars:
    project:
      repo: '/root/cuboid.git/.git'
      stage_dir: '/root/stage'
    ssh_pub_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDopS2Gw1Kf93QFj/UclZwtSB+74A82zLW8ndSw519U7CAUYTPnFDgjknPvMIyf0Nc2KDMfE5+7Mt3UARm6FbiRoSbbdsyjWdjAnZYV84ir2LTuoSQJL0bJCtkQ+ghE8ywGhU+HslTh7WOo6G3CcEtPe89dFCKm2uTzOf3h75ouHqsYnP+UFUFxsylilNhZkNRo4GW9OgWQQVDtUdDenfeHlj17wIBqyhiwvj6Xw5TPEJZU3rVOsSd0KboWxheLbA/sIDtfT+Kdb2DB+TwjHuciCiXyutOY4zq7E7s9TfRVb0XyaZeyF+u9P3tSKeedUc3wf6CxzwJdHOeJYbfH7YS5 thomas.moericke'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3nRFGFfof+N7GuTdY3n5DXlSgzgx38UPT0AZvQXVHNs0xatBd6TB59DBXsFqQ3999cqVYcFoWS55PIIo9kPgTBYIBvqzDcxHf/cOlE9ncNOsfdKsqZOYTDaPe5shdoBCN+bTZrfLuv+q5GlzLyhzE2lsKyDvuH+yrcSGpOONd1WjUyjNhYVaE/pW+XxLFUwu7Ey7gBFbhL2cHT5y0sjCyzTYEcGZJCmzie6WVFXDycKxtSCNinx14LWPn4CG8Dw2mC2y8rnZ/P4i5r1oDrdLngv6JBCknCvF4sYE49MayYZJqBEdNZiVSS0gT6rvFDYZiLEneEbXFpS86QFda+hRn elmar.gerdes'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUYT8uhHPKnNvKgK1ns6y2PoFWQ0B9+SijcYOLkt5fT+MvE4Kb2CibPipSX6XtiCctcB1o460hCqxG4pDAIYAeYyiH1kpCg58/cMcFJnkE3MVSO/i/kAkXh+ub6DVFf0EDKrp/SwgmxO9hAy3bas7jyCxtqaC6Csu6zMV9Cx3hCDnhsyi2+6cnwQgemsvzMS1w3NtbExguLO4V6GsEaPsT+AsE6tl3Ge19WAOdiZ3jflVenabbnBiwDCOoazIPEx5K7CCBk897D4EzjmDs/wy9dsiTweGbSpuOc2KbpoeEtYb6avxoEadTEsbeFIFioXtVcmFP6cNiLf+NwKu57pcl peter.stehfest' 
  children:
    deployment:
      hosts:
        85.215.221.22
      vars:
        ansible_repo: /root/ansible.git

    cuboid:
      hosts:
        85.215.239.34
      vars:
        cuboid_dir: '/opt/cuboid'
    masha:
      hosts:
        85.215.233.125


