- name: systemd_reload
  systemd:
    daemon_reload: yes

- name: cuboid_restart
  systemd:
    name: 'cuboid.service'
    state: restarted

- name: nginx_restart
  systemd:
    name: nginx
    state: restarted
