ok: [200,201,202,203,204,205,206]

knownsrv: {}
knownNics: []
knownVolumes: {}
lanOK: false
ips: {}

contract:
  url: 'https://api.ionos.com/cloudapi/v6'
  user: 'platform-compute-assessment+4@cloud.ionos.com'
  password: 'scewd/2Ov'

rz:
  properties:
    name: 'DevOps Autotest'
    location: 'de/txl'
    secAuthProtection: false

lan:
  properties:
    name: 'foo'
    public: true

servers:
  - properties:
      name: cuboid
      cores: 1
      ram: 2048
      availabilityZone: 'AUTO' 
      cpuFamily: 'INTEL_SKYLAKE'
      type: 'ENTERPRISE'

  - properties:
      name: mariadb
      cores: 1
      ram: 2048
      availabilityZone: 'AUTO' 
      cpuFamily: 'INTEL_SKYLAKE'
      type: 'ENTERPRISE'
nics:
  cuboid:
    properties:
      name: cuboid
      lan: 1
      dhcp: true
      firewallActive: false
      firewallType: 'INGRESS'

  mariadb:
    properties:
      name: mariadb
      lan: 1
      dhcp: true
      firewallActive: false
      firewallType: 'INGRESS'
     
volumes:
  cuboid:
   properties:
     name: cuboid
     type: HDD
     size: 10
     image: 'ef452aa5-8307-11ec-bda6-02086196891f'
     bus: VIRTIO
     imagePassword: 'ionos1u1'
     sshKeys: ['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDw3aw63qxwYf41pvWKblNl80KzFRPtw160lihhJYqWvwHJhQk090UzrYJuRsYZrW9TU0uezRBOQS6RNX68djgpJenehA9visBtOxODfZFnw/0KZKPS0+/gMskWtvcXHm475e7HNv+cesXcMyYV5cxW7ObyI+N3CAoYXUN5V+y+IMY8WLzMNGD049wzUyRThcvG7NC1E9TYU1g6I+awQ1lLCr4htWNeSGXW5kCZRFjN9M2d0yvHN926/yA7Gaw4Bp8V4HOWQycqeniLZ0YOybn7PAzAxe85CjnhHSTjVDLmr3YBnLwPLN3XEiJ6ZZDKdRxQZw2sXl9XnSrMmYApvlBjpWQ3x0ptTYYBXkhrqjrIOyoBVPayGVnVzUulOeZwnhM+PutCoV1rVENADjxr8fRBDNnCLa+ZTjoebk4mpMk+zRuWbBwn/3ZRUiFEoRndfkBGK8DJQmzXDI6+qm3bSRIZ+87NH+yMRSi2URaDWDcMXaIo9KQWMTF2Ge/F0Go42Lk= tom@bomdia']

  mariadb:
   properties:
     name: mariadb
     type: HDD
     size: 10
     image: 'ef452aa5-8307-11ec-bda6-02086196891f'
     bus: VIRTIO
     imagePassword: 'ionos1u1'


