---
- name: 'Install the tools'
  package:
    name:
      - 'git'
      - 'cmake'
    state: latest

- name: 'Clone the project'
  git:
    repo: "{{project.repo}}"
    dest: "{{project.stage_dir}}"

- name: 'Build'
  make:
    chdir: "{{project.stage_dir}}"


