---
- name: 'Install packages'
  package:
    name: 
      - 'nginx'
      - 'python3-pip'
      - 'python3-venv'
      - 'libpcre3'
      - 'libpcre3-dev'
      - 'vim'

- name: 'Find exact name of a wheel'
  find:
    paths:
      - "{{project.stage_dir}}/dist"
    file_type: file
    patterns:
      - 'cuboid-*.whl'
  register: the_wheel
  delegate_to: localhost

- name: 'Wheel name as a fact'
  set_fact:
    wheel_path: "{{the_wheel['files'][0]['path']}}"
    wheel_name: "{{the_wheel['files'][0]['path'] | basename}}"

- name: 'Copy the wheel'
  copy:
    src: "{{wheel_path}}"
    dest: "/tmp/{{wheel_name}}"

- name: 'Install in venv'
  pip:
    name:
      - pip
      - wheel
      - "/tmp/{{wheel_name}}"
    state: latest
    virtualenv: "{{cuboid_dir}}"
    virtualenv_command: python3 -m venv

- name: 'Create user cuboid for running a wsgi app'
  user:
    name: cuboid
    groups:
      - 'www-data'
    append: yes

- name: 'Create config dir'
  file:
    path: '/opt/cuboid/etc'
    state: directory
    mode: 0755
    owner: root
  with_items:
    - '/opt/cuboid/etc'
    - '/opt/cuboid/run'

- name: 'Copy wsgi config'
  copy: 
    src: 'wsgi.ini'
    dest: '/opt/cuboid/etc/'
    mode: 0644
    owner: root

- name: 'Copy app config'
  template:
    src: 'cuboid.cfg.j2'
    dest: '/opt/cuboid/etc/'
    mode: 0644
    owner: root

- name: 'systemd service'
  copy:
    src: 'cuboid.service'
    dest: '/etc/systemd/system/'
    mode: 0644
    owner: root
    group: root
  notify: 
    - systemd_reload
    - cuboid_restart

- name: 'Flush handlers'
  meta: flush_handlers

- name: 'Cuboid systemd service'
  systemd:
    name: 'cuboid.service'
    state: started
    enabled: yes

- name: 'Disable default nginx site'
  file:
    state: absent
    path: '/etc/nginx/sites-enabled/default'

- name: 'nginx config as proxy'
  copy: 
    src: 'nginx_cuboid_config'
    dest: '/etc/nginx/sites-available/'
  notify: nginx_restart
    
- name: 'Activate nginx proxy config'
  file:
    state: link
    src: '/etc/nginx/sites-available/nginx_cuboid_config'
    path: '/etc/nginx/sites-enabled/nginx_cuboid_config'
  notify: nginx_restart

- name: 'nginx service'
  systemd:
    name: nginx
    state: started
    enabled: yes

