---
- name: 'Install packages'
  package:
    name: 
      - 'nginx'
      - 'python3-pip'
      - 'python3-venv'

- name: 'Find exact name of a wheel'
  find:
    paths:
      - "{{project.stage_dir}}/dist"
    file_type: file
    patterns:
      - 'cuboid-*.whl'
  register: the_wheel
  delegate_to: localhost

- name: 'Wheel name as a fact'
  set_fact:
    wheel_path: "{{the_wheel['files'][0]['path']}}"
    wheel_name: "{{the_wheel['files'][0]['path'] | basename}}"

- name: 'Copy the wheel'
  copy:
    src: "{{wheel_path}}"
    dest: "/tmp/{{wheel_name}}"

- name: 'Install in venv'
  pip:
    name:
      - pip
      - wheel
      - "/tmp/{{wheel_name}}"
    state: latest
    virtualenv: "{{cuboid_dir}}"
    virtualenv_command: python3 -m venv

- name: 'Create user cuboid for running a wsgi app'
  user:
    name: cuboid
    groups:
      - 'www-data'
    append: yes

- name: 'Copy config dir'
  copy:
    src: 'cuboidapp'
    dest: '/opt/'
    mode: 0644
    owner: cuboid

- name: 'systemd service'
  copy:
    src: 'cuboid.service'
    dest: '/etc/systemd/system/'
    mode: 0644
    owner: root
    group: root
  notify: 
    - systemd_reload
    - cuboid_restart

- name: 'Cuboid systemd service'
  systemd:
    name: 'cuboid.service'
    state: started
    enabled: yes
